/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookapp;

/**
 * BookGUI.java
 * 12/08/2023
 * @author Michael E.
 */
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
public class BookGUI extends javax.swing.JFrame {
    private ArrayList<Book> books;
    /**
     * Creates new form BookGUI
     */
    public BookGUI() {
        initComponents();
        books = new ArrayList<Book>();
        fileFormatTF.setVisible(false);
        narratorTF.setVisible(false);
        fileFormatLbl.setVisible(false);
        narratorLbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookTypeBG = new javax.swing.ButtonGroup();
        bookCatalogueLbl = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        titleLbl = new javax.swing.JLabel();
        titleTF = new javax.swing.JTextField();
        authorLbl = new javax.swing.JLabel();
        authorTF = new javax.swing.JTextField();
        costLbl = new javax.swing.JLabel();
        costTF = new javax.swing.JTextField();
        fileFormatLbl = new javax.swing.JLabel();
        fileFormatTF = new javax.swing.JTextField();
        narratorLbl = new javax.swing.JLabel();
        narratorTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bookRB = new javax.swing.JRadioButton();
        eBookRB = new javax.swing.JRadioButton();
        audioBookRB = new javax.swing.JRadioButton();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        mostExpensiveBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        loadBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookDetailsTA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookCatalogueLbl.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        bookCatalogueLbl.setText("Book Catalogue");

        idLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idLbl.setText("ID:");

        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleLbl.setText("Title:");

        authorLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        authorLbl.setText("Author:");

        costLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        costLbl.setText("Cost:");

        fileFormatLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fileFormatLbl.setText("File Format:");

        fileFormatTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileFormatTFActionPerformed(evt);
            }
        });

        narratorLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        narratorLbl.setText("Narrator:");

        jLabel1.setText("Select type of book you want below");

        bookTypeBG.add(bookRB);
        bookRB.setText("Hard Copy");
        bookRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRBActionPerformed(evt);
            }
        });

        bookTypeBG.add(eBookRB);
        eBookRB.setText("E-Book");
        eBookRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBookRBActionPerformed(evt);
            }
        });

        bookTypeBG.add(audioBookRB);
        audioBookRB.setText("Audio Book");
        audioBookRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioBookRBActionPerformed(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        displayBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        mostExpensiveBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mostExpensiveBtn.setText("Highest Costing Book");
        mostExpensiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostExpensiveBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        loadBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        loadBtn.setText("Load");
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        bookDetailsTA.setColumns(20);
        bookDetailsTA.setRows(5);
        jScrollPane1.setViewportView(bookDetailsTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(bookCatalogueLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idLbl)
                                    .addComponent(titleLbl)
                                    .addComponent(authorLbl)
                                    .addComponent(costLbl)
                                    .addComponent(fileFormatLbl)
                                    .addComponent(narratorLbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(140, 140, 140)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(authorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(costTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fileFormatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(narratorTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(bookRB)
                                    .addComponent(eBookRB)
                                    .addComponent(audioBookRB)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mostExpensiveBtn)
                                .addGap(30, 30, 30)
                                .addComponent(loadBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBtn)
                                .addGap(29, 29, 29)
                                .addComponent(displayBtn)
                                .addGap(30, 30, 30)
                                .addComponent(saveBtn)
                                .addGap(30, 30, 30)
                                .addComponent(searchBtn)))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookCatalogueLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bookRB)
                                .addGap(18, 18, 18)
                                .addComponent(eBookRB)
                                .addGap(18, 18, 18)
                                .addComponent(audioBookRB))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idLbl)
                                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(titleLbl)
                                    .addComponent(titleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(authorLbl)
                                    .addComponent(authorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(costLbl)
                                    .addComponent(costTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fileFormatLbl)
                                    .addComponent(fileFormatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(narratorLbl)
                                    .addComponent(narratorTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBtn)
                            .addComponent(displayBtn)
                            .addComponent(saveBtn)
                            .addComponent(searchBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostExpensiveBtn)
                    .addComponent(loadBtn))
                .addGap(114, 114, 114))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRBActionPerformed
        // TODO add your handling code here:
        fileFormatLbl.setVisible(false);
        fileFormatTF.setVisible(false);
        narratorLbl.setVisible(false);
        narratorTF.setVisible(false);
    }//GEN-LAST:event_bookRBActionPerformed

    private void eBookRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBookRBActionPerformed
        // TODO add your handling code here:
        fileFormatLbl.setVisible(true);
        fileFormatTF.setVisible(true);
        narratorLbl.setVisible(false);
        narratorTF.setVisible(false);
    }//GEN-LAST:event_eBookRBActionPerformed

    private void audioBookRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioBookRBActionPerformed
        // TODO add your handling code here:
        narratorLbl.setVisible(true);
        narratorTF.setVisible(true);
        fileFormatLbl.setVisible(false);
        fileFormatTF.setVisible(false);
    }//GEN-LAST:event_audioBookRBActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        if(bookRB.isSelected()){
            Book b = new Book();
            b.setIdNum(idTF.getText());
            b.setTitle(titleTF.getText());
            b.setAuthor(authorTF.getText());
            b.setCost(Double.parseDouble(costTF.getText()));
            
            books.add(b);
            bookDetailsTA.append("New hard copy added to catalogue\n");
        }
        else if(eBookRB.isSelected()){
            EBook e = new EBook();
            e.setIdNum(idTF.getText());
            e.setTitle(titleTF.getText());
            e.setAuthor(authorTF.getText());
            e.setCost(Double.parseDouble(costTF.getText()));
            e.setFileFormat(fileFormatTF.getText());
            
            books.add(e);
            bookDetailsTA.append("New E-Book added to catalogue\n");
        }
        else if(audioBookRB.isSelected()){
            AudioBook a = new AudioBook();
            a.setIdNum(idTF.getText());
            a.setTitle(titleTF.getText());
            a.setAuthor(authorTF.getText());
            a.setCost(Double.parseDouble(costTF.getText()));
            a.setNarrator(narratorTF.getText());
            
            books.add(a);
            bookDetailsTA.append("New audio book added to catalogue\n");
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<books.size(); i++){
            Book b1 = books.get(i);
            JOptionPane.showMessageDialog(null, b1.getDetails());
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTFActionPerformed

    private void fileFormatTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileFormatTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileFormatTFActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        File f;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            f = new File("Book Catalogue.dat");
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(books);
            oStream.close();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        bookDetailsTA.append("Books saved to catalogue");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
        // TODO add your handling code here:
        File f;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            f = new File("Book Catalogue.dat");
            fStream = new FileInputStream(f);
            oStream = new ObjectInputStream(fStream);
            
            books = (ArrayList<Book>)oStream.readObject();
            oStream.close();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null, e);
        }
        catch(ClassNotFoundException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_loadBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String searchId;
        searchId = JOptionPane.showInputDialog(null, "Enter the ID of the book you want to search for");
        for(Book b:books){
            if(b.getIdNum().equals(searchId)){
                JOptionPane.showMessageDialog(null, b.getDetails());
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed
    
    //@ Reference: https://www.geeksforgeeks.org/finding-maximum-element-of-java-arraylist/
    //Author: shekharsaxena316
    //The getMostExpensive method was inspired by the reference above
    public Book getMostExpensive(){
        Book mostExpensive = books.get(0);
        for(Book b:books){
            if(mostExpensive.getCost() < b.getCost()){
                mostExpensive = b;
            }
        }
        return mostExpensive;
    }
    
    private void mostExpensiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostExpensiveBtnActionPerformed
        // TODO add your handling code here:
        Book mostExpensiveBook = getMostExpensive(); 
        if(mostExpensiveBook != null){
            JOptionPane.showMessageDialog(null, "The most expensive book\n" + mostExpensiveBook.getDetails());
        }
        else{
            JOptionPane.showMessageDialog(null, "Please enter details for the cost of a book");
        }
    }//GEN-LAST:event_mostExpensiveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JRadioButton audioBookRB;
    private javax.swing.JLabel authorLbl;
    private javax.swing.JTextField authorTF;
    private javax.swing.JLabel bookCatalogueLbl;
    private javax.swing.JTextArea bookDetailsTA;
    private javax.swing.JRadioButton bookRB;
    private javax.swing.ButtonGroup bookTypeBG;
    private javax.swing.JLabel costLbl;
    private javax.swing.JTextField costTF;
    private javax.swing.JButton displayBtn;
    private javax.swing.JRadioButton eBookRB;
    private javax.swing.JLabel fileFormatLbl;
    private javax.swing.JTextField fileFormatTF;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadBtn;
    private javax.swing.JButton mostExpensiveBtn;
    private javax.swing.JLabel narratorLbl;
    private javax.swing.JTextField narratorTF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField titleTF;
    // End of variables declaration//GEN-END:variables
}
